language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-26

install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;2.0.0-alpha2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;2.0.0-alpha2"

before_script:
- chmod +x gradlew

script:
- ./gradlew build
- ./gradlew test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
